export const SUBMIT_REGISTER_REQUESTED = 'SUBMIT_REGISTER_REQUESTED';
export const SUBMIT_REGISTER_SUCCESS = 'SUBMIT_REGISTER_SUCCESS';
export const SET_FORM_REGISTER = 'SET_FORM_REGISTER';
export const SUBMIT_REGISTER_ERROR = 'SUBMIT_REGISTER_ERROR';