export const FETCH_DASHBOARD_MENU = 'FETCH_DASHBOARD_MENU';
export const FETCH_DASHBOARD_MENU_SUCCESS = 'FETCH_DASHBOARD_MENU_SUCCESS';
export const FETCH_DASHBOARD_MENU_ERROR = 'FETCH_DASHBOARD_MENU_ERROR';