export const FETCH_RECOMENDATION_MENU = 'FETCH_RECOMENDATION_MENU';
export const FETCH_RECOMENDATION_MENU_SUCCESS = 'FETCH_RECOMENDATION_MENU_SUCCESS';
export const FETCH_RECOMENDATION_MENU_ERROR = 'FETCH_RECOMENDATION_MENU_ERROR';