//GET
export const FETCH_CHILD_DATA = 'FETCH_CHILD_DATA';
export const FETCH_CHILD_DATA_SUCCESS = 'FETCH_CHILD_DATA_SUCCESS';
export const FETCH_CHILD_DATA_ERROR = 'FETCH_CHILD_DATA_ERROR';

// DELETE
export const DELETE_CHILD_DATA = 'DELETE_CHILD_DATA';
export const DELETE_CHILD_DATA_SUCCESS = 'DELETE_CHILD_DATA_SUCCESS';
export const DELETE_CHILD_DATA_ERROR = 'DELETE_CHILD_DATA_ERROR';

// ADD
export const ADD_CHILD_DATA = 'ADD_CHILD_DATA';
export const ADD_CHILD_DATA_SUCCESS = 'ADD_CHILD_DATA_SUCCESS';
export const ADD_CHILD_DATA_ERROR = 'ADD_CHILD_DATA_ERROR';

//SET FORM
export const SET_FORM_CHILD_DATA = 'SET_FORM_CHILD_DATA';