export const SUBMIT_LOGIN_REQUESTED = 'SUBMIT_LOGIN_REQUESTED';
export const SUBMIT_LOGIN_SUCCESS = 'SUBMIT_LOGIN_SUCCESS';
export const SET_FORM_LOGIN = 'SET_FORM_LOGIN';
export const SUBMIT_LOGIN_ERROR = 'SUBMIT_LOGIN_ERROR';